# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terragrunt-tf-state-241533159018-eu-west-1"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "dev/eu-west-1/vpc/terraform.tfstate"
    region         = "eu-west-1"
  }
}
